"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['spider.py']
DATA_FILES = []
OPTIONS = {'includes': ['bs4.BeautifulSoup', 're', 'urllib.request','urllib.error','xlwt','datetime','xlrd','os','requests','PIL.Image','shutil'],}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
